# Generated by Django 5.1.4 on 2025-05-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ci',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula de Identidad'),
        ),
    ]
