# Generated by Django 5.1.4 on 2025-05-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_userprofile_ci'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitularDePermisosDeAccesoAModulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permiso de Acceso a Módulo',
                'verbose_name_plural': 'Permisos de Acceso a Módulos',
                'permissions': [('acceder_modulo_administracion', 'Puede acceder al módulo de Administración del Sistema'), ('acceder_modulo_reportes', 'Puede acceder al módulo de Reportes de Asistencia'), ('acceder_modulo_planillas', 'Puede acceder al módulo de Planillas (Bono TE)'), ('acceder_modulo_sueldos', 'Puede acceder al módulo de Sueldos'), ('acceder_modulo_boletas', 'Puede acceder al módulo de Boletas')],
                'managed': False,
            },
        ),
    ]
