# Generated by Django 5.1.4 on 2025-05-27 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_titulardepermisosdeaccesoamodulos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitularDePermisosDeAccesoAModulos',
        ),
    ]
