# Generated by Django 5.1.4 on 2025-05-04 22:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planilla', '0002_detallebonote_abandono_dias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(help_text='Mes numérico (1-12)', verbose_name='Mes')),
                ('anio', models.IntegerField(help_text='Año (ej: 2024)', verbose_name='Año')),
                ('tipo', models.CharField(choices=[('planta', 'Personal Permanente'), ('contrato', 'Contrato')], help_text='Tipo de personal al que corresponde', max_length=40, verbose_name='Tipo Planilla')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('cargado', 'Excel Cargado'), ('validado', 'Validado'), ('pagado', 'Pagado'), ('archivado', 'Archivado'), ('error_carga', 'Error en Carga')], default='borrador', help_text='Estado actual de la planilla de sueldos', max_length=15, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('archivo_excel_cargado', models.FileField(blank=True, help_text='Archivo .xlsx original que se procesó', null=True, upload_to='sueldos_excel/%Y/%m/', verbose_name='Archivo Excel Cargado')),
                ('fecha_carga_excel', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Carga Excel')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales o resumen/errores del proceso de carga del Excel', null=True, verbose_name='Observaciones / Resumen Carga')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_sueldo_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
            ],
            options={
                'verbose_name': 'Planilla de Sueldos',
                'verbose_name_plural': 'Planillas de Sueldos',
                'db_table': 'sueldo_planilla',
                'ordering': ['-anio', '-mes', 'tipo'],
                'unique_together': {('mes', 'anio', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='DetalleSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_trab', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna G del Excel', max_digits=5, verbose_name='Días Trab.')),
                ('haber_basico', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna H del Excel', max_digits=12, verbose_name='HABER BASICO')),
                ('categoria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna I del Excel (¿Bono Antigüedad?)', max_digits=10, verbose_name='CATEGORIA')),
                ('total_ganado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna J del Excel', max_digits=12, verbose_name='TOTAL GANADO')),
                ('rc_iva_retenido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna K del Excel', max_digits=10, verbose_name='RC-IVA Retenido')),
                ('gestora_publica', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna L del Excel (¿Aporte AFP?)', max_digits=10, verbose_name='GESTORA PUBLICA')),
                ('aporte_nac_solidario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna M del Excel', max_digits=10, verbose_name='Aporte Nac. Solidario')),
                ('cooperativa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna N del Excel', max_digits=10, verbose_name='Cooperativa')),
                ('faltas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna O del Excel (Monto de descuento)', max_digits=10, verbose_name='Faltas')),
                ('memorandums', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna P del Excel (Monto de descuento)', max_digits=10, verbose_name='Memorandums')),
                ('otros_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna Q del Excel', max_digits=10, verbose_name='Otros Descuentos')),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna R del Excel', max_digits=12, verbose_name='TOTAL DESCUENTOS')),
                ('liquido_pagable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna S del Excel', max_digits=12, verbose_name='LIQUIDO PAGABLE')),
                ('item_referencia', models.IntegerField(blank=True, help_text='Columna B del Excel', null=True, verbose_name='Item (Referencia Excel)')),
                ('nombre_completo_referencia', models.CharField(blank=True, help_text='Columna D del Excel', max_length=300, null=True, verbose_name='Nombre Completo (Referencia Excel)')),
                ('cargo_referencia', models.CharField(blank=True, help_text='Columna E del Excel', max_length=300, null=True, verbose_name='Cargo (Referencia Excel)')),
                ('fecha_ingreso_referencia', models.DateField(blank=True, help_text='Columna F del Excel', null=True, verbose_name='Fecha Ingreso (Referencia Excel)')),
                ('fila_excel', models.IntegerField(blank=True, help_text='Número de fila original en el archivo Excel', null=True, verbose_name='Nro Fila Excel')),
                ('personal_externo', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_sueldo', to='planilla.principalpersonalexterno', verbose_name='Personal Externo')),
                ('planilla_sueldo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_sueldo', to='sueldos.planillasueldo', verbose_name='Planilla de Sueldos')),
            ],
            options={
                'verbose_name': 'Detalle de Sueldo',
                'verbose_name_plural': 'Detalles de Sueldo',
                'db_table': 'sueldo_detalle',
                'ordering': [models.OrderBy(models.F('personal_externo__apellido_paterno'), nulls_last=True), models.OrderBy(models.F('personal_externo__apellido_materno'), nulls_last=True), models.OrderBy(models.F('personal_externo__nombre'), nulls_last=True)],
                'unique_together': {('planilla_sueldo', 'personal_externo')},
            },
        ),
    ]
