# Generated by Django 5.1.4 on 2025-06-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sueldos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadomensualempleado',
            options={'ordering': ['-cierre_mensual__anio', '-cierre_mensual__mes', 'pk'], 'verbose_name': 'Detalle Estado Mensual Empleado', 'verbose_name_plural': 'Detalles Estados Mensuales Empleados'},
        ),
    ]
