# Generated by Django 5.1.4 on 2025-06-07 19:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueldos', '0003_detallesueldo_sanciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesueldo',
            name='aporte_nac_solidario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna M del Excel', max_digits=12, verbose_name='Aporte Nac. Solidario'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='categoria',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna I del Excel (¿Bono Antigüedad?)', max_digits=12, verbose_name='CATEGORIA'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='cooperativa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna N del Excel', max_digits=12, verbose_name='Cooperativa'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='faltas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna O del Excel (Monto de descuento)', max_digits=12, verbose_name='Faltas'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='gestora_publica',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna L del Excel (¿Aporte AFP?)', max_digits=12, verbose_name='GESTORA PUBLICA'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='memorandums',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna P del Excel (Monto de descuento)', max_digits=12, verbose_name='Memorandums'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='otros_descuentos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna Q del Excel', max_digits=12, verbose_name='Otros Descuentos'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='sanciones',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de descuento por sanciones (típico de planillas de contrato)', max_digits=12, verbose_name='Sanciones'),
        ),
    ]
