# Generated by Django 5.1.4 on 2025-06-07 19:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueldos', '0004_alter_detallesueldo_aporte_nac_solidario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesueldo',
            name='cooperativa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna N del Excel', max_digits=10, verbose_name='Cooperativa'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='memorandums',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna P del Excel (Monto de descuento)', max_digits=10, verbose_name='Memorandums'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='rc_iva_retenido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna K del Excel', max_digits=12, verbose_name='RC-IVA Retenido'),
        ),
    ]
