# Generated by Django 5.1.4 on 2025-06-10 02:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueldos', '0005_alter_detallesueldo_cooperativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesueldo',
            name='lactancia_prenatal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bono de lactancia o prenatal. No proviene del Excel.', max_digits=12, verbose_name='Lactancia / Prenatal'),
        ),
        migrations.AddField(
            model_name='detallesueldo',
            name='otros_ingresos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Otros ingresos adicionales no contemplados en el Excel.', max_digits=12, verbose_name='Otros Ingresos'),
        ),
        migrations.AddField(
            model_name='detallesueldo',
            name='saldo_credito_fiscal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna T Saldo RC-IVA.', max_digits=12, verbose_name='Saldo Crédito Fiscal.'),
        ),
    ]
