# Generated by Django 5.1.4 on 2025-06-10 03:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueldos', '0006_detallesueldo_lactancia_prenatal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesueldo',
            name='aporte_nac_solidario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna M del Excel', max_digits=12, verbose_name='APORTE SOLIDARIO NAL.'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='cooperativa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna N del Excel', max_digits=10, verbose_name='COOPERATIVA'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='dias_trab',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna G del Excel', max_digits=5, verbose_name='DIAS TRAB.'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='faltas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna O del Excel (Monto de descuento)', max_digits=12, verbose_name='FALTAS'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='lactancia_prenatal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bono de lactancia o prenatal. No proviene del Excel.', max_digits=12, verbose_name='LACTANCIA PRENATAL'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='memorandums',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna P del Excel (Monto de descuento)', max_digits=10, verbose_name='MEMORANDUMS'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='otros_descuentos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna Q del Excel', max_digits=12, verbose_name='OTROS DESCUENTOS'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='otros_ingresos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Otros ingresos adicionales no contemplados en el Excel.', max_digits=12, verbose_name='OTROS INGRESOS'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='saldo_credito_fiscal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna T Saldo RC-IVA.', max_digits=12, verbose_name='SALDO CREDITO FISCAL.'),
        ),
        migrations.AlterField(
            model_name='detallesueldo',
            name='sanciones',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de descuento por sanciones (típico de planillas de contrato)', max_digits=12, verbose_name='SANCIONES'),
        ),
    ]
