# Generated by Django 5.1.4 on 2025-06-10 03:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueldos', '0007_alter_detallesueldo_aporte_nac_solidario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesueldo',
            name='rc_iva_retenido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Columna K del Excel', max_digits=12, verbose_name='RC-IVA RETENIDO'),
        ),
    ]
