# Generated by Django 5.1.4 on 2025-07-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueldos', '0008_alter_detallesueldo_rc_iva_retenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierremensual',
            name='tipo_planilla',
            field=models.CharField(choices=[('planta', 'Personal Permanente'), ('contrato', 'Contrato')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='planillasueldo',
            name='tipo',
            field=models.CharField(choices=[('planta', 'Personal Permanente'), ('contrato', 'Contrato')], help_text='Tipo de personal al que corresponde', max_length=40, verbose_name='Tipo Planilla'),
        ),
    ]
