# Generated by Django 5.1.4 on 2025-05-07 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalCargoExterno',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(blank=True, db_column='Nombre_cargo', max_length=80, null=True)),
            ],
            options={
                'db_table': 'principal_cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrincipalDesignacionExterno',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('item', models.IntegerField(blank=True, db_column='Item', null=True)),
                ('tipo_designacion', models.CharField(blank=True, db_column='tipo', max_length=50, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=20, null=True)),
                ('fecha_conclusion', models.DateField(blank=True, db_column='Fecha_conclusion', null=True)),
                ('fecha_ingreso', models.DateField(blank=True, db_column='Fecha_ingreso', null=True)),
            ],
            options={
                'db_table': 'principal_designacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrincipalPersonalExterno',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('apellido_paterno', models.CharField(blank=True, db_column='A_Paterno', max_length=50, null=True)),
                ('apellido_materno', models.CharField(blank=True, db_column='A_Materno', max_length=50, null=True)),
                ('ci', models.CharField(blank=True, db_column='CI', max_length=10, null=True, unique=True)),
            ],
            options={
                'db_table': 'principal_personal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrincipalSecretariaExterna',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre_secretaria', models.CharField(blank=True, db_column='Nombre_secretaria', max_length=100, null=True)),
            ],
            options={
                'db_table': 'principal_secretaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrincipalUnidadExterna',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre_unidad', models.CharField(blank=True, db_column='Nombre_unidad', max_length=86, null=True)),
            ],
            options={
                'db_table': 'principal_unidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('fecha_elaboracion', models.DateField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('ufvi', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('ufvf', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('smn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_dias', models.IntegerField(blank=True, null=True)),
                ('importe_diario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('planta', 'Asegurado'), ('contrato', 'Contrato'), ('consultor', 'Consultor en Linea')], max_length=40, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('dias_habiles', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Días Hábiles del Mes')),
                ('usuario_aprobacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_elaboracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_elaboradas', to=settings.AUTH_USER_MODEL)),
                ('usuario_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBonoTe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mes (Heredado)')),
                ('abandono_dias', models.DecimalField(decimal_places=2, default=0, help_text='Días registrados como abandono de trabajo.', max_digits=10, verbose_name='Abandono (días)')),
                ('faltas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Faltas (días)')),
                ('viajes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Viajes (días)')),
                ('pcgh', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='PCGH (días)')),
                ('psgh', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='PSGH (días)')),
                ('perm_excep', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Perm. Excep. (días)')),
                ('asuetos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Asuetos (días)')),
                ('pcgh_embar_enf_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='PCGH Emb/Enf Base (días)')),
                ('vacacion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vacación (días)')),
                ('bajas_medicas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bajas Médicas (días)')),
                ('dias_no_pagados', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Días No Pagados (Calculado)')),
                ('dias_pagados', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Días Pagados (Calculado)')),
                ('total_ganado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Ganado Bono (Calculado)')),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Otros Descuentos al Bono')),
                ('liquido_pagable', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Líquido Pagable Bono (Calculado)')),
                ('rc_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='RC-IVA (¿Aplica al bono?)')),
                ('dias_cancelados', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Días Cancelados')),
                ('otros_descuentos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Otros Descuentos (Duplicado?)')),
                ('observaciones_asistencia', models.TextField(blank=True, help_text='Notas registradas en el detalle de asistencia para este periodo.', null=True, verbose_name='Observaciones (Copiado de Asistencia)')),
                ('observaciones_bono', models.TextField(blank=True, help_text='Notas específicas sobre este registro de Bono TE o ediciones realizadas.', null=True, verbose_name='Observaciones (Bono TE)')),
                ('personal_externo', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_bono_te', to='planilla.principalpersonalexterno', verbose_name='Personal Externo')),
                ('id_planilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_bono_te', to='planilla.planilla', verbose_name='Planilla')),
            ],
            options={
                'verbose_name': 'Detalle de Bono TE',
                'verbose_name_plural': 'Detalles de Bono TE',
                'db_table': 'detalle_bono_te',
            },
        ),
    ]
