# Generated by Django 5.1.4 on 2025-04-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallebonote',
            name='abandono_dias',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Días registrados como abandono de trabajo.', max_digits=10, verbose_name='Abandono (días)'),
        ),
    ]
