# Generated by Django 5.1.4 on 2025-05-20 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0001_initial'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='planilla_asistencia_base',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planilla_bono_te_generada', to='reportes.planillaasistencia', verbose_name='Planilla de Asistencia Base'),
        ),
    ]
