# Generated by Django 5.1.4 on 2025-07-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0003_remove_detallebonote_abandono_dias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='principalcargoexterno',
            options={'default_permissions': (), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='principaldesignacionexterno',
            options={'default_permissions': (), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='principalpersonalexterno',
            options={'default_permissions': (), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='principalsecretariaexterna',
            options={'default_permissions': (), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='principalunidadexterna',
            options={'default_permissions': (), 'managed': False},
        ),
    ]
