# Generated by Django 5.1.4 on 2025-07-03 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0004_alter_principalcargoexterno_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='principalcargoexterno',
            options={'managed': False, 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='principaldesignacionexterno',
            options={'managed': False, 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='principalpersonalexterno',
            options={'managed': False, 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='principalsecretariaexterna',
            options={'managed': False, 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='principalunidadexterna',
            options={'managed': False, 'permissions': []},
        ),
    ]
