# Generated by Django 5.1.4 on 2025-02-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0004_alter_planilla_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallebonote',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='detallebonote',
            name='dias_comiciones',
        ),
        migrations.RemoveField(
            model_name='detallebonote',
            name='dias_total',
        ),
        migrations.RemoveField(
            model_name='detallebonote',
            name='nitem',
        ),
        migrations.RemoveField(
            model_name='detallebonote',
            name='rc_iva',
        ),
        migrations.RemoveField(
            model_name='detallebonote',
            name='total_descuentos',
        ),
        migrations.AddField(
            model_name='detallebonote',
            name='asuetos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Asuetos'),
        ),
        migrations.AddField(
            model_name='detallebonote',
            name='descuentos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuentos'),
        ),
        migrations.AddField(
            model_name='detallebonote',
            name='dias_habiles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Dias Habiles'),
        ),
        migrations.AddField(
            model_name='detallebonote',
            name='dias_no_pagados',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Dias no Pagados'),
        ),
        migrations.AddField(
            model_name='detallebonote',
            name='dias_pagados',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Dias Pagados'),
        ),
        migrations.AddField(
            model_name='detallebonote',
            name='dias_total_trab',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Días Total Trabajados'),
        ),
        migrations.AddField(
            model_name='detallebonote',
            name='pcgh_embar_enf_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='PCGH Embarazada Efermedad de Base'),
        ),
        migrations.AddField(
            model_name='detallebonote',
            name='perm_excep',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Perm_Excep'),
        ),
        migrations.AddField(
            model_name='detallebonote',
            name='psgh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='PSGH'),
        ),
    ]
