# Generated by Django 5.1.4 on 2025-02-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0005_remove_detallebonote_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallebonote',
            name='rc_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='RC-IVA'),
        ),
    ]
