# Generated by Django 5.1.4 on 2025-07-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0005_alter_principalcargoexterno_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='tipo',
            field=models.CharField(blank=True, choices=[('planta', 'Asegurado'), ('contrato', 'Contrato')], max_length=40, null=True),
        ),
    ]
