# Generated by Django 5.1.4 on 2025-02-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0006_detallebonote_rc_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallebonote',
            name='dias_cancelados',
        ),
        migrations.AddField(
            model_name='detallebonote',
            name='viajes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Viajes'),
        ),
    ]
