# Generated by Django 5.1.4 on 2025-02-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0007_remove_detallebonote_dias_cancelados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallebonote',
            name='viajes',
        ),
        migrations.AddField(
            model_name='detallebonote',
            name='dias_cancelados',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Días Cancelados'),
        ),
    ]
