# Generated by Django 5.1.4 on 2025-02-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0009_detallebonote_viajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallebonote',
            name='tipo',
            field=models.CharField(blank=True, choices=[('salud', 'Salud'), ('riesgo', 'Riesgo'), ('otro', 'Otro')], max_length=40, null=True),
        ),
    ]
