# Generated by Django 5.1.4 on 2025-02-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0010_detallebonote_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallebonote',
            name='tipo',
        ),
        migrations.AddField(
            model_name='detallebonote',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallebonote',
            name='fecha_elaboracion',
            field=models.DateField(auto_now_add=True),  # Eliminar default=1
        ),
        migrations.AddField(
            model_name='detallebonote',
            name='fecha_revision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallebonote',
            name='mes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Mes'),
        ),
    ]
