# Generated by Django 5.1.4 on 2025-03-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0012_remove_detallebonote_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallebonote',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fin'),
        ),
        migrations.AddField(
            model_name='detallebonote',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
