# Generated by Django 5.1.4 on 2025-03-19 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0013_detallebonote_fecha_fin_detallebonote_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleimpositiva',
            name='id_bonote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_impositiva', to='planilla.detallebonote', verbose_name='Bonote'),
        ),
    ]
