# Generated by Django 5.1.4 on 2025-03-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0014_detalleimpositiva_id_bonote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleimpositiva',
            name='id_bonote',
        ),
    ]
