# Generated by Django 5.1.4 on 2025-03-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0016_alter_detallebonote_asuetos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallebonote',
            name='asuetos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Asuetos'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='bajas_medicas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Bajas Médicas'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='descuentos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Descuentos'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='dias_cancelados',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Días Cancelados'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='dias_habiles',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Dias Habiles'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='dias_no_pagados',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Dias no Pagados'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='dias_pagados',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Dias Pagados'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='dias_total_trab',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Días Total Trabajados'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='faltas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Faltas'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='liquido_pagable',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Líquido Pagable'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='otros_descuentos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Otros Descuentos'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='pcgh',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='PCGH'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='pcgh_embar_enf_base',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='PCGH Embarazada Efermedad de Base'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='perm_excep',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Perm_Excep'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='psgh',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='PSGH'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='rc_iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='RC-IVA'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='total_ganado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total Ganado'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='vacacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Vacación'),
        ),
        migrations.AlterField(
            model_name='detallebonote',
            name='viajes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Viajes'),
        ),
    ]
