# Generated by Django 5.1.4 on 2025-04-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0021_principalpersonal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleimpositiva',
            name='id_personal',
        ),
        migrations.RemoveField(
            model_name='detallesueldo',
            name='id_personal',
        ),
        migrations.RemoveField(
            model_name='detallebonote',
            name='id_personal',
        ),
        migrations.RemoveField(
            model_name='detallesueldo',
            name='id_unidad',
        ),
        migrations.RemoveField(
            model_name='detallebonote',
            name='id_unidad',
        ),
        migrations.RemoveField(
            model_name='detalleimpositiva',
            name='id_unidad',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
        migrations.DeleteModel(
            name='Unidad',
        ),
    ]
