# Generated by Django 5.1.4 on 2025-04-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0023_principalcargoexterno_principaldesignacionexterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='tipo',
            field=models.CharField(blank=True, choices=[('planta', 'Planta'), ('contrato', 'Contrato'), ('consultor', 'Consultor')], max_length=40, null=True),
        ),
    ]
