# Generated by Django 5.1.4 on 2025-04-22 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planilla', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(help_text='Mes al que corresponde la asistencia (1-12).', verbose_name='Mes')),
                ('anio', models.IntegerField(help_text='Año al que corresponde la asistencia.', verbose_name='Año')),
                ('tipo', models.CharField(choices=[('planta', 'Asegurado'), ('contrato', 'Contrato'), ('consultor', 'Consultor en Linea')], help_text='Tipo de personal al que aplica esta asistencia.', max_length=40, verbose_name='Tipo de Planilla')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('completo', 'Completo'), ('validado', 'Validado'), ('rechazado', 'Rechazado'), ('archivado', 'Archivado')], default='borrador', help_text='Estado actual del proceso de recopilación de asistencia.', max_length=15, verbose_name='Estado del Reporte')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Validación')),
                ('observaciones_generales', models.TextField(blank=True, help_text='Notas adicionales sobre esta planilla de asistencia.', null=True, verbose_name='Observaciones Generales')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_asistencia_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
                ('usuario_validacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_asistencia_validadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Validación')),
            ],
            options={
                'verbose_name': 'Planilla de Asistencia',
                'verbose_name_plural': 'Planillas de Asistencia',
                'db_table': 'reporte_planilla_asistencia',
                'ordering': ['-anio', '-mes', 'tipo'],
                'unique_together': {('mes', 'anio', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='DetalleAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omision_cant', models.IntegerField(default=0, help_text='Cantidad de veces que omitió marcar entrada/salida.', verbose_name='Nro. Omisiones Marcado')),
                ('omision_sancion', models.DecimalField(decimal_places=2, default=0, help_text='Valor de la sanción por omisión (monetario o factor).', max_digits=10, verbose_name='Sanción Omisión')),
                ('abandono_dias', models.DecimalField(decimal_places=2, default=0, help_text='Días registrados como abandono de trabajo.', max_digits=5, verbose_name='Abandono (días)')),
                ('abandono_sancion', models.DecimalField(decimal_places=2, default=0, help_text='Valor de la sanción por abandono (monetario o factor).', max_digits=10, verbose_name='Sanción Abandono')),
                ('faltas_dias', models.DecimalField(decimal_places=2, default=0, help_text='Días de falta injustificada.', max_digits=5, verbose_name='Faltas (días)')),
                ('faltas_sancion', models.DecimalField(decimal_places=2, default=0, help_text='Valor de la sanción por faltas (monetario o factor).', max_digits=10, verbose_name='Sanción Faltas')),
                ('atrasos_minutos', models.IntegerField(default=0, help_text='Total de minutos de atraso acumulados en el periodo.', verbose_name='Atrasos (minutos)')),
                ('atrasos_sancion', models.DecimalField(decimal_places=2, default=0, help_text='Valor de la sanción por atrasos (monetario o factor).', max_digits=10, verbose_name='Sanción Atrasos')),
                ('vacacion', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Vacación (días)')),
                ('viajes', models.DecimalField(decimal_places=2, default=0, help_text='Días en viaje oficial o comisión.', max_digits=5, verbose_name='Viajes (días)')),
                ('bajas_medicas', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Bajas Médicas (días)')),
                ('pcgh', models.DecimalField(decimal_places=2, default=0, help_text='Permiso Con Goce de Haber.', max_digits=5, verbose_name='PCGH (días)')),
                ('perm_excep', models.DecimalField(decimal_places=2, default=0, help_text='Permiso Excepcional (con o sin goce, según normativa).', max_digits=5, verbose_name='Perm. Excep. (días)')),
                ('asuetos', models.DecimalField(decimal_places=2, default=0, help_text='Días de asueto oficial reconocidos.', max_digits=5, verbose_name='Asuetos (días)')),
                ('lsgh', models.DecimalField(decimal_places=2, default=0, help_text='Licencia Sin Goce de Haber.', max_digits=5, verbose_name='LSGH (días)')),
                ('pcgh_embar_enf_base', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='PCGH Emb/Enf Base (días)')),
                ('actividad_navidad', models.DecimalField(decimal_places=2, default=0, help_text='Días relacionados con actividad navideña (permiso, asistencia, etc.).', max_digits=5, verbose_name='Act. Navidad (días)')),
                ('iza_bandera', models.DecimalField(decimal_places=2, default=0, help_text='Días relacionados con la iza de bandera (permiso, asistencia, etc.).', max_digits=5, verbose_name='Iza Bandera (días)')),
                ('observaciones', models.TextField(blank=True, help_text='Notas sobre este registro de asistencia en particular.', null=True, verbose_name='Observaciones Específicas')),
                ('personal_externo', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_asistencia', to='planilla.principalpersonalexterno', verbose_name='Personal Externo')),
                ('planilla_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_asistencia', to='reportes.planillaasistencia', verbose_name='Planilla de Asistencia')),
            ],
            options={
                'verbose_name': 'Detalle de Asistencia',
                'verbose_name_plural': 'Detalles de Asistencia',
                'db_table': 'reporte_detalle_asistencia',
                'unique_together': {('planilla_asistencia', 'personal_externo')},
            },
        ),
    ]
