# Generated by Django 5.1.4 on 2025-07-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planillaasistencia',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('validado', 'Validado'), ('archivado', 'Archivado')], default='borrador', help_text='Estado actual del proceso de recopilación de asistencia.', max_length=15, verbose_name='Estado del Reporte'),
        ),
    ]
