# Generated by Django 5.1.4 on 2025-04-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleasistencia',
            name='lsgh',
        ),
        migrations.AddField(
            model_name='detalleasistencia',
            name='psgh',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Permiso Sin Goce de Haber.', max_digits=5, verbose_name='PSGH (días)'),
        ),
    ]
