"""
Django settings for sisboletas project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from decimal import Decimal # Asegúrate de tener esta importación si la necesitas en otro lugar
from django.db import models # Asegúrate de tener esta importación si la necesitas en otro lugar

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^a1@l@yaln^rwjqk1g)c00w#%&@mo7vyl_82^eoutjht^0f&qt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# settings.py

# ... (otras configuraciones) ...

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler', # Envía a stderr (consola)
        },
    },
    'root': { # Logger raíz
        'handlers': ['console'],
        'level': 'INFO', # Muestra INFO, WARNING, ERROR, CRITICAL
    },
    'loggers': {
        'django': { # Logger específico para Django
            'handlers': ['console'],
            'level': 'INFO', # O 'DEBUG' para más detalle
            'propagate': False,
        },
    }
}





INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'auditlog', 
    'administracion.apps.AdministracionConfig',
    'widget_tweaks',
    'planilla.apps.PlanillaConfig', 
    'reportes.apps.ReportesConfig',
    'sueldos.apps.SueldosConfig',
    'boletas.apps.BoletasConfig',
    'bitacora.apps.BitacoraConfig',
    'core',
    'axes',

]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'sisboletas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # --- Corregido: Usar BASE_DIR que es un objeto Path ---
        'DIRS': [BASE_DIR / 'plantillas'], # Busca en la carpeta 'plantillas' de tu proyecto
        'APP_DIRS': True, # Busca plantillas dentro de las apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sisboletas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sisboletas',
        'USER': 'postgres',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'personas_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sigap_personal_simulacion',
        'USER': 'postgres',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-bo'
TIME_ZONE = 'America/La_Paz'
USE_I18N = True
USE_TZ = True # Recomendado mantener en True


# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/' 

# --- Directorios adicionales donde buscar archivos estáticos (además de las apps) ---
STATICFILES_DIRS = [
    BASE_DIR / 'static', # Busca en la carpeta 'static' de tu proyecto (a nivel de manage.py)
]

# --- Directorio donde collectstatic copiará TODOS los archivos estáticos para PRODUCCIÓN ---

STATIC_ROOT = BASE_DIR / 'staticfiles'



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Opcional: Configuración de Mensajes (si usas Bootstrap) ---
# from django.contrib.messages import constants as messages_constants
# MESSAGE_TAGS = {
#     messages_constants.DEBUG: 'alert-secondary',
#     messages_constants.INFO: 'alert-info',
#     messages_constants.SUCCESS: 'alert-success',
#     messages_constants.WARNING: 'alert-warning',
#     messages_constants.ERROR: 'alert-danger',
# }



LOGIN_URL = 'login'


LOGIN_REDIRECT_URL = 'index' 


LOGOUT_REDIRECT_URL = 'login'

# ----------------------------------------------------

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# --- CONFIGURACIÓN DE DJANGO-AXES ---

AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend debe ser el primero para interceptar los logins
    'axes.backends.AxesStandaloneBackend',

    # Tu backend por defecto, que se ejecutará si Axes lo permite
    'django.contrib.auth.backends.ModelBackend',
]

# Número de intentos fallidos permitidos antes de bloquear.
AXES_FAILURE_LIMIT = 5

# Tiempo de enfriamiento (bloqueo) en horas.
# 0.25 = 15 minutos, 0.5 = 30 minutos, 1 = 1 hora
AXES_COOLOFF_TIME = 1

# Qué combinación de credenciales se usa para contar los fallos.
# Por defecto es solo por IP. Es más seguro incluir el username.
# Esto significa: "bloquea después de 5 intentos fallidos desde la misma IP
# O después de 5 intentos fallidos para el mismo nombre de usuario (incluso desde diferentes IPs)".
AXES_LOCKOUT_PARAMETERS = ["ip_address", "username"]

# Si quieres que el usuario vea una página de error 403 (Forbidden) en lugar de la de login
# cuando está bloqueado, pon esto en True. Es más seguro porque no da pistas.
AXES_LOCK_OUT_AT_FAILURE = True

# Si quieres recibir un email cada vez que alguien es bloqueado (requiere configurar emails en Django)
# AXES_ENABLE_ADMIN_NOTIFICATIONS = True