# Generated by Django 5.1.4 on 2025-05-07 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Plantilla')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('datos_diseno_json', models.JSONField(default=dict, verbose_name='Datos del Diseño (JSON)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('es_predeterminada', models.BooleanField(default=False, verbose_name='Usar como predeterminada')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_boleta_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
            ],
            options={
                'verbose_name': 'Plantilla de Boleta',
                'verbose_name_plural': 'Plantillas de Boletas',
                'ordering': ['nombre'],
            },
        ),
    ]
