# Generated by Django 5.1.4 on 2025-05-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillaboleta',
            name='tamano_pagina',
            field=models.CharField(choices=[('LETTER', 'Carta (8.5 x 11 pulgadas)'), ('LEGAL', 'Oficio / Legal (8.5 x 14 pulgadas)'), ('A4', 'A4 (210 x 297 mm)')], default='LETTER', max_length=20, verbose_name='Tamaño de Página'),
        ),
    ]
